### ISSUE TITLE
Can you provide some description for the project?

### ISSUE THREAD

**Issue by octref** [mdn/stumptown-content#298]
Hey, I see that https://github.com/mdn/short-descriptions is archived and this is the active project now. However I cannot find any much information on the high-level goals. I only find some bits in the wiki. Here are some of my questions I hope you could clarify for me:

- Will this project provide HTML/CSS properties' short descriptions as a node module?
- What does this project aim to achieve? Seems to be a revamping of HTML/CSS sections on MDN to me. No need to answer if this is not public yet.

**Comment by wbamberg** [comment]
> Will this project provide HTML/CSS properties' short descriptions as a node module?

It will eventually provide short descriptions, yes. As a node module, maybe.

> What does this project aim to achieve?

It aims to change the way we create and represent MDN's content. The idea is to maintain our docs in GitHub, and to explicitly represent (and lint for) structure for the reference docs, rather than just treating them as unstructured blobs of HTML.

We expect people to author content in a mixture of Markdown (for prose) and YAML (for data). There are rules about what an author can and must include in the documentation for a given item, and CI will enforce these rules. We have a build step that converts this documentation as-authored into a single JSON object for each item. A consumer of this JSON can build MDN web pages from it, but it's our intention to make the JSON available to other consumers too.

So yes, you should be able to access the short description, but also other things like executable examples associated with an item, or the list of methods defined for a JS object, or the specification that defines an item, or... well, how much depends on how deep we go defining structure initially.

> if this is not public yet

It's not "not public" but at the moment we're still at an early and quite experimental stage. We're currently trying to figure out how we can migrate our content into this form, using the JS documentation as a guinea pig.

**Comment by octref** [comment]
Hey @wbamberg, thanks for the clarification.

I'll keep an eye on this project. Externalizing the content management into Git sounds great, as you can leave version control, PR, etc to Git. Having the data in a structured form would allow others to easily reuse them.

Good luck! At VS Code we manage our docs as Markdown files with some metadata as well: https://github.com/microsoft/vscode-docs. For example:
- [MD file](https://raw.githubusercontent.com/microsoft/vscode-docs/master/blogs/2019/10/31/inspecting-containers.md)
- [Rendered MD file](https://github.com/microsoft/vscode-docs/blob/master/blogs/2019/10/31/inspecting-containers.md)

Let me know if there's anything I might be able to help.
