### ISSUE TITLE
Fix linting errors "dt elements in link lists must contain a single anchor element"

### ISSUE THREAD

**Issue by Elchi3** [mdn/stumptown-content#407]
432 errors javascript-class/data.instance_methods
129 errors javascript-class/data.instance_properties
69 errors   javascript-class/data.static_methods
49 errors   javascript-class/data.static_properties
38 errors   javascript-namespace/data.static_methods
9 errors     javascript-namespace/data.static_properties
8 errors     javascript-namespace/data.constructor_properties

= 734 errors and thus the majority of all errors we currently have when linting all of the JS MDN docs.

I believe we can fix this by either allowing or by removing `jsxref` macros in `<dt>`

**Comment by wbamberg** [comment]
-> https://github.com/mdn/stumptown-content/pull/419: we should now tolerate `jsxref` in lnk lists.

**Comment by Elchi3** [comment]
Thanks Will! This reduced the error amount drastically. Remaining:


---
52 errors      javascript-class/data.instance_properties?/only-single-anchor-element-or-xref-in-link-list-dt
3 errors       javascript-class/data.instance_methods?/only-single-anchor-element-or-xref-in-link-list-dt
1 error        javascript-class/data.static_methods?/only-single-anchor-element-or-xref-in-link-list-dt

**Comment by Elchi3** [comment]
@wbamberg what did we decide about readonly inline banners? The remaining failures seem to be about that. See e.g. https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array#Instance_properties

**Comment by wbamberg** [comment]
We talked about this here: https://github.com/mdn/sprints/issues/2520.

`readonlyinline` is mostly problematic to remove when it's not attached to a link. When a badge is attached to a link, we think it is OK to remove, because we think the linked page will tell the reader that the thing is read only (or experimental, or whatever), via a banner in the target page.

But by definition, in "link lists" the badge will always be attached to a link. And in the example you gave of https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array#Instance_properties, the linked pages do indicate that the property is read only (although not using a banner).

In the page you linked to, the `dd` content also says that the property is read only, so I think it would be fine to remove the macro calls (in fact it looks weird having both).

**Comment by Elchi3** [comment]
I've removed the macro calls (also given its rendering is broken) and added "ready only" in the dd text if it wasn't already there.

Some other fixes were needed but I have now cleared all errors of this kind.
