### ISSUE TITLE
Handler for data.interactive_example?

### ISSUE THREAD

**Issue by Elchi3** [mdn/stumptown-content#408]
There are many warnings about a missing handler for interactive_examples.
Should we add a handler that checks if the macro call

`{{EmbedInteractiveExample("pages/js/array-foreach.html")}}`

and the text 

> The source for this interactive example is stored in a GitHub repository. If you'd like to contribute to the interactive examples project, please clone https://github.com/mdn/interactive-examples and send us a pull request.

is present?

---

434 warnings   javascript-method/data.interactive_example?/handler-not-implemented
99 warnings    javascript-property/data.interactive_example?/handler-not-implemented                       
73 warnings    javascript-language-feature/data.interactive_example?/handler-not-implemented               
57 warnings    javascript-class/data.interactive_example?/handler-not-implemented                          
56 warnings    javascript-constructor/data.interactive_example?/handler-not-implemented 
7 warnings     javascript-namespace/data.interactive_example?/handler-not-implemented

## Acceptance criteria

The linter checks for the `data.interactive_example?` ingredient against the spec.

**Comment by wbamberg** [comment]
We have a spec for this handler already: https://github.com/mdn/stumptown-content/blob/master/project-docs/javascript-linter-spec.md#datainteractive_example.

All optional ingredients are tricky. You can't just check that the macro call is present, because if the ingredient is optional, then omitting the macro call is valid. See also https://github.com/mdn/stumptown-content/pull/391#discussion_r405835899 where this is discussed at great length.

If there's no extra structure to check, then "is this optional ingredient correct" just collapses into "if this ingredient is present at all, is it in the right place", so I thought it would be implicitly checked by linting ingredient order.

But first, this leaves us with "handler-not-implemented" warnings, and second, after the discussion in https://github.com/mdn/stumptown-content/pull/391#discussion_r405835899, we did end up defining some extra structure to check. So yes, we should probably add a handler for this.

**Comment by wbamberg** [comment]
This should be fixed by https://github.com/mdn/stumptown-content/pull/416.
