### ISSUE TITLE
U - Handler for prose.description?

### ISSUE THREAD

**Issue by Elchi3** [mdn/stumptown-content#409]
There are many warnings about a missing handler for prose.description.
Can we silence them or come up with a handler?

I would expect it to have `<h2>Description</h2>` and at least one `<p>`.

---
434 warnings   javascript-method/prose.description?/handler-not-implemented
99 warnings    javascript-property/prose.description?/handler-not-implemented                              
73 warnings    javascript-language-feature/prose.description?/handler-not-implemented                      
57 warnings    javascript-class/prose.description?/handler-not-implemented                                 
56 warnings    javascript-constructor/prose.description?/handler-not-implemented                           
7 warnings      javascript-namespace/prose.description?/handler-not-implemented                             
6 warnings      landing-page/prose.description?/handler-not-implemented                                     

## Acceptance criteria

We have an ingredient handler for `prose.description?`

**Comment by wbamberg** [comment]
This is an optional ingredient. With the mandatory prose ingredients, we lint them by checking that the expected H2 heading exists. But with an optional prose ingredient, what do you do? It obviously doesn't make sense to have a test like:

does the page have H2#Description->pass
does the page omit H2#Description->pass

> I would expect it to have `<h2>Description</h2>` **and at least one `<p>`.**

Yes, we could require that it has a `<p>`. But we don't for the other prose ingredients. Are we just doing it here to manufacture a theoretical failure case? And how likely is it that a page will contain an H2#Description without a `<p>` - that is, how much will a test like this really contribute to doc quality?

The real significance of `prose.description?` is that it's saying: "if the page has this section, then it must appear in this place". So I thought that the test for this ingredient really collapses into the ingredient order test.

If it's important for the ingredient order test to have a handler, as was discussed in the meeting we had the other day, then we could add one. Otherwise, if we want to suppress the warning for this ingredient, we could add an explicitly "always pass" handler for it. That seems more honest. Either way though I don't think a handler for this will generate more errors, so I don't think this should have to block "fixing all lint errors".

**Comment by Elchi3** [comment]
> Yes, we could require that it has a `<p>`. But we don't for the other prose ingredients. Are we just doing it here to manufacture a theoretical failure case? And how likely is it that a page will contain an H2#Description without a `<p>` - that is, how much will a test like this really contribute to doc quality?

For linked lists we are quite strict and only allow a single `<dl>`. I had many cases where the markup was dirty and the `<dl>` was wrapped in `<div>` cruft or the like and it produced linting errors. So, I don't know if such a test would help here to avoid these things in Description sections as well.  And yes, this isn't really doc quality, but rather markup quality. 

> Otherwise, if we want to suppress the warning for this ingredient, we could add an explicitly "always pass" handler for it. That seems more honest.

Right, always pass handler would work for me. Essentially it is a free form prose section anyway.

>  Either way though I don't think a handler for this will generate more errors, so I don't think this should have to block "fixing all lint errors".

I agree, I mainly filed this so that all errors/warnings get our attention now, because I thought that we will likely see them forever and some might be quite noisy, so maybe it is better to silence them if they add no benefit for us.

**Comment by ddbeck** [comment]
I've assigned this to myself. As @wbamberg mentioned in #420, this is probably necessary to fully resolve #338 (along with other optional ingredients).
