### ISSUE TITLE
U - Write recipe for CSS functions

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#439]
This issue is split out of https://github.com/mdn/stumptown-content/issues/396, which wants us to write recipes for all the CSS reference documentation page types.

I thought to keep things a bit easier to follow it might make sense to have issues to track different CSS recipes. This one is for **CSS functions**. 

# Acceptance Criteria 
- [ ] recipe for CSS function pages is written and checked into stumptown-content
- [ ] spec for how to lint with this recipe is written and checked into stumptown-content

**Comment by wbamberg** [comment]
# CSS functions

I count 57 CSS function pages. They have more or less a form like:

Short description
Interactive example
H2. Syntax
H2. Accessibility concerns (occasionally)
H2. Examples
H2. Specifications
H2. Browser compatibility
H2. See also

## filter-function and transform-function

We can split the CSS functions into three groups:

* 11 under https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function/, that represent possible values for the `<filter-function>` type.
* 21 under https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/transform-function/, that represent possible values for the `<transform-function>` type
* the rest, which live directly under https://wiki.developer.mozilla.org/en-US/docs/Web/CSS

(Note that one function - `url()` - lived in two groups: [`CSS/url()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url())  and [`CSS/filter-function/url`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function/url). @a2sheppy just made the second of these redirect to the first one, which I think is the right call, but more filter-specific content should be added to the remaining page. I've filed https://github.com/mdn/sprints/issues/3243 for this.)

The pages under "CSS/filter-function/" are much thinner than the others, all lacking "Specifications" and "Browser compatibility".

The pages under "CSS/transform-function" include "Specifications" and "Browser compatibility" sections, but "Browser compatibility" just points to the [`<transform-function>`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/transform-function#Browser_compatibility) page: the individual transform functions don't have their own compat data.

So we should decide whether the filter-function and transform-function pages should be treated differently from the other function pages, or not. If they should be treated the same, we should consider whether we should add BCD for them and any other missing bits. If they should be treated differently, what are they anyway?

I think we should treat them the same, and take on the work of giving them consistent structure and content.

## Syntax

All the filter-function and transform-function pages omit `{{csssyntax}}` in the "H2#Syntax" section and many of the others do, too. In fact I reckon 44/57 pages have no call to `{{csssyntax}}`. That doesn't mean there isn't a structure, though.

The filter-function pages have:

```
H2 Syntax
  non-formal syntax code block
  H3 Parameters
    parameters DL
```

For example: [`blur()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function/blur#Syntax), [`hue-rotate()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function/hue-rotate#Syntax).

The transform-function pages have:

```
H2 Syntax
  prose introduction
  informal syntax code block
  H3 Values
    values DL
```

For example: [`scale()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale#Syntax), [`translate3d()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate3d#Syntax).

The remaining pages use a lot of different structures, featuring various constructs like:

* prose
* informal syntax code blocks
* H3 Values
* H3 Formal syntax

The "Formal syntax", where it exists, usually does use the real formal syntax notation, but is often included in the page as literal text rather than from mdn/data using through a call to `{{csssyntax}}`. See for example [`linear-gradient`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient#Syntax). Often it does not match the syntax given in the spec.

Other times (13 times out of 57 pages total) it does include formal syntax from mdn/data using `{{csssyntax}}`. For example: [`clamp()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/clamp#Syntax), [`image()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/imagefunction#Syntax).

So... this section is a bit of a mess really. I don't think it is worth adding formal syntax into mdn/data for the function that are currently missing it. So I don't think it's worth giving this page type a `data.formal_syntax` ingredient. Perhaps it would be best just to treat the H2#Syntax as prose, as we have done so far for JS method pages.

**Comment by Elchi3** [comment]
Thanks for another great research into our doc structures, Will!

---

#### Single page vs multiple pages

> So we should decide whether the filter-function and transform-function pages should be treated differently from the other function pages, or not. If they should be treated the same, we should consider whether we should add BCD for them and any other missing bits. If they should be treated differently, what are they anyway?
> 
> I think we should treat them the same, and take on the work of giving them consistent structure and content.

So, if we treat them the same, the I suppose we will run into "context problems" (as discussed recently for the compat ingredient), that is, we will have two or more have compat tables, spec references, example code, etc. which need to address two or more contexts.

In a way, this reminds me of "mixins". In order to not repeat definitions, the specs often define features as mixins that are then referenced in multiple interfaces. Here, it is functionality that is shared on multiple CSS properties.

However, some functionality, like `clamp()`, seems to be usable on many (potentially hundreds) of properties, so there we can't go with separate pages. Also, in that case it isn't really a "mixin". Rather, we can maybe compare this to HTML global attributes vs HTML element specific attributes. In CSS, I don't know how many are "global functions" (available broadly throughout CSS)  vs. functions shared only between 2-3 properties. Also, I don't know if we need to treat this differently or if our collection of "CSS functions" should make availability clear. I guess, as a CSS developer, I want to know about this, but I can't tell from own experience.

----

#### Syntax

Given these are functions, a concept that a developer might know from other languages outside of CSS, I'm quite surprised these need to be described using the (arguably rather cryptic) CSS formal syntax. Would it be possible to describe CSS function (mostly their parameters) in the same way we describe JS method syntax? (maybe this is a naive question, but I really don't know all that much about CSS)

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/stumptown-content/pull/497.
