### ISSUE TITLE
U- Write recipe for CSS selectors

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#440]
This issue is split out of https://github.com/mdn/stumptown-content/issues/396, which wants us to write recipes for all the CSS reference documentation page types.

I thought to keep things a bit easier to follow it might make sense to have issues to track different CSS recipes. This one is for **CSS selectors**. 

# Acceptance Criteria 
- [ ] recipe for CSS selector pages is written and checked into stumptown-content
- [ ] spec for how to lint with this recipe is written and checked into stumptown-content

**Comment by wbamberg** [comment]
# CSS Selectors (pseudoclasses and pseudoelements)

I think there are about 137 pages here. 71 are prefixed (40 moz, 14 ms, 17 webkit).

The unprefixed ones have a fairly consistent structure:

* short description
* static code example (see for example  [`::grammar-error`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error))
* optional more prose
* H2#Syntax
* H2#Allowable/permitted properties (optional)
* H2#Accessibility concerns (optional)
* H2#Examples
* H2#Specifications
* H2#Browser compatibility
* H2#See also

A few things worth considering:

## The static code example at the start

These pages don't have interactive examples, but generally have a static code block instead, in the same place. So options here are:

1. Don't structure/enforce this, but just treat the static code example as part of a prose H2#Description section.
2. Don't structure/enforce this, but just treat the static code example as part of a prose H2#Syntax section (if we treat that as prose rather than formal syntax, see below).
3. Invent a new ingredient that's a static code sample.

I think I'd favour (2).

## H2#Syntax

* This usually contains the formal syntax via a call to `{{csssyntax}}`, and only the formal syntax (i.e. no prose description of the syntax, no `{{cssinfo}}`. 

* Occasionally it does not use the formal syntax (e.g. [`::grammar-error`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error)).

* Occasionally it uses the formal syntax and a prose description (e.g. [`:dir`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:dir#Syntax) ).

* The formal syntax is almost always extremely simple (e.g. [`:active`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:active#Syntax)).

* When formal syntax is complex is seems to be always because it's referring to the `<complex-selector-list>` or `<relative-selector-list>` types, which it then expands (e.g. [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has)).

In this case I think we should remove the `{{csssyntax}}` calls and just represent the syntax as prose. In cases like [`:active`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:active#Syntax) I don't think it adds anything, and in the complex cases like [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has) the syntax seems totally opaque. It would be better to have a prose definition of what we mean by `<complex-selector-list>` - either a short description in place or a longer one that these pages can link to.

## H2#Allowable/permitted properties

This is not a particularly common section but it crops up a few times. I'm on the fence about whether we should define a named prose section for it, or let it be a custom prose section.

## Prefixed pages

More than half of these pages are for prefixed pseudoclasses and pseudoelements. These are in general much less consistent than the unprefixed ones. Many of them are missing BCD and other mandatory sections.

Some of them are no longer supported by anyone, and I think we should archive these. For the rest though I think we will have to add the missing information. Potentially that's quite a bit of work...

## Proposal

All that leaves us with a recipe that could look like:

```yaml
data:
  - title
  - short_title?
  - mdn_url
body:
  - prose.short_description
  - prose.syntax             // including static code sample
  - prose.description?
  - prose.permitted_properties?
  - prose.accessibility_concerns?
  - prose.*
  - data.examples
  - data.specifications
  - data.browser_compatibility
  - prose.see_also
```

**Comment by wbamberg** [comment]
(Comment from Daniel)
******
Thanks, Will. This one looks pretty promising to me. Just a couple points I had thoughts on:

- `prose.syntax` (including a static code sample) seems suspiciously similar to `data.formal_definition_and_syntax` ingredient we agreed on for CSS properties. Are these things really different from each other? In particular, you decided against removing `{{csssyntax}}` for properties and it's not clear to me why they're ripe for removal in selector pages.
- `H2#Allowable/permitted properties`: I'm inclined to make these explicit ingredients. I worry that `prose.*` will become a junk drawer for half-standardized ingredients. If we can structure it, let's do it.

**Comment by wbamberg** [comment]
> Thanks, Will. This one looks pretty promising to me. Just a couple points I had thoughts on:
> 
> * `prose.syntax` (including a static code sample) seems suspiciously similar to `data.formal_definition_and_syntax` ingredient we agreed on for CSS properties. Are these things really different from each other? In particular, you decided against removing `{{csssyntax}}` for properties and it's not clear to me why they're ripe for removal in selector pages.
> 

I think removing `{{csssyntax}}` makes more sense for selectors than it does for property pages.

We could (and do) argue about whether formal syntax is useful to include in property pages, but there's no question that:

* specs for properties present "Value" syntax in a very consistent way: [`transform`](https://drafts.csswg.org/css-transforms/#transform-property), [`background-size`](https://drafts.csswg.org/css-backgrounds-3/#the-background-size), [`gap`](https://drafts.csswg.org/css-align-3/#propdef-gap). 

* the value is often complex in a way that's hard to express in prose, and is very variable from one property to another.

With selectors, most of the time the syntax is trivial: [`:active`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:active#Syntax), [`::placeholder`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#Syntax), [`:hover`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:hover#Syntax) and in these cases the spec doesn't elaborate syntax for each selector at all (e.g. [`:active`](https://drafts.csswg.org/selectors-4/#active-pseudo)). What value is formal syntax adding in these cases?

Sometimes, when the selector is given arguments, then the syntax is more complex ([`:dir()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:dir#Formal_syntax), [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has#Syntax), [`:host()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:host()#Syntax). In cases like this the specification does provide a formal description of the syntax (e.g. [`:has()`](https://drafts.csswg.org/selectors-4/#relational). But in almost all these cases, as far as I can make out, the formal syntax describes some types of selectors (compound selectors, relative selectors, complex selectors) and I think it would be **much** more helpful in these cases to have some prose documentation (dry, but prose) describing what these selector types all are, and then pointing to this documentation from the prose syntax section for a particular pseudo-class. As it happens the spec already does this (https://drafts.csswg.org/selectors-4/#structure) and I think this is much more useful than repeating the formal syntax of `<complex-selector>` on every page. So we ought to provide good documentation of what the different selector types are, cribbed from the spec, then link to it.

(I would be very open to removing formal syntax from properties as well, but I do think this case is more debatable.)

> * `prose.syntax` (including a static code sample) seems suspiciously similar to `data.formal_definition_and_syntax` ingredient we agreed on for CSS properties. 

I think it is much more like the `prose.syntax` that we have already for the [javascript-method](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-method.yaml) recipes : basically, the thing we use when we have decided not to structure the syntax description.

******

But that aside, suppose we decided formal syntax was useful for selectors? How would we want to represent it in a recipe? Would we want something like `data.formal_syntax` that's an H2#Formal_syntax, whose contents is a `{{csssyntax}}` call? Would we worry that the underlying data here is essentially the same as part of the `data.formal_definition_and_syntax` ingredient that we've proposed for CSS properties? So would this lead to us wanting to break up `data.formal_definition_and_syntax` into two separate ingredients? And if we did *that*, would we then fret that our ingredients currently only map to H2 headings (so we don't really have a way to define `data.formal_syntax` except as a top-level heading?

I think one thing we're coming up against here is a tension between:
* the "structured content" idea, which wants to say "these things have formal syntax data associated with them. How you represent them in the page is a problem for the renderer" and 
* the "lint HTML pages" idea, which is very concerned with how the HTML itself is organized.

The CSS property page wants a rendered representation like:

```
H2 Formal definition and syntax

H3 Formal definition
{{cssinfo}}

H3 Formal syntax
{{csssyntax}}
```

The CSS selector page doesn't have formal definition. If we wanted to keep formal syntax, I'd probably want to split it out into its own top level section:

```
H2 Formal syntax
{{csssyntax}}
```

...and keep `prose.syntax` as an informal description.

Then for recipes, css-property could have:

```
...
data.formal_definition
data.formal_syntax
...
```

...and css-selector could have:


```
...
data.formal_syntax
...
```

...and the linter's specification could be:

* for `data.formal_syntax`: look for a heading at any level with an ID of "Formal_syntax", and it must contain only the `{{csssyntax}}` call. 
* for `data.formal_definition`: look for a heading at any level with an ID of "Formal_syntax", and it must contain only the `{{cssinfo}}` call.

(part of the reason I'm going into this is that I've been looking at CSS functions, and a similar question crops up there.)

**Comment by wbamberg** [comment]
> * `H2#Allowable/permitted properties`: I'm inclined to make these explicit ingredients. I worry that `prose.*` will become a junk drawer for half-standardized ingredients. If we can structure it, let's do it.

Very good point! Thanks for keeping me honest!  :-P

That said: at the moment this doesn't appear very often in the pages. I'm not sure whether that means it should appear more often, or that we should not make it an explicit part of the recipe. But if we do, yes I agree with your point here.

**Comment by Elchi3** [comment]
Thanks, Will! Nice work!

---
#### Static code samples at the top and css syntax

> Don't structure/enforce this, but just treat the static code example as part of a prose H2#Syntax section (if we treat that as prose rather than formal syntax, see below).

I think I'd prefer this, too.

> I think removing `{{csssyntax}}` makes more sense for selectors than it does for property pages.

That seems like a good idea and potentially a good test for removing csssyntax elsewhere later on.

> Sometimes, when the selector is given arguments, then the syntax is more complex ([`:dir()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:dir#Formal_syntax), [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has#Syntax), [`:host()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:host()#Syntax).) 

This reminds me of the JS docs where [4 years ago I argued](https://groups.google.com/forum/#!msg/mozilla.dev.mdc/eS12O5mAI-A/J1Qd-HajBgAJ) that instead of listing formal syntax we should list all variations of how to call a function as it is more readable. Apparently, this was reverted in the JS docs by various contributors, but I still think syntax notations are unhelpful. When Jean-Yves and I then started the HTTP docs section, we didn't chose to display IETF header formal syntax but listed all options ([example](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control)).
Sure, formal syntax is structured data that is useful to offer (to potential tools), but I would say the larger use case is MDN readers that actually need to decide how to use the feature, and I don't think formal syntax is alĺ that helpful or copy-pastable. So, I'd vote for "surface" structure for the moment and lay this out as useful as possible for MDN readers, and opt-in for "deep" structure for when we think we really need to offer structure of formal syntax of things.

--- 

#### Description vs prose.* vs own ingredient

>    `H2#Allowable/permitted properties`: I'm inclined to make these explicit ingredients. I worry that `prose.*` will become a junk drawer for half-standardized ingredients. If we can structure it, let's do it.

I think a question that arises here is when to (a) make something an ingredient, when to (b) accept it as a top-level custom h2 as part of prose.* and when to (c) make it part of prose.description, which, arguably, could also become a junk drawer. 

I think I would have put this as an h3 in the description ingredient if it doesn't happen all that often. It doesn't seem to be all that important to deserve a spot as a top-level h2 item, but I'm not actually a subject matter expert on this. But I think there should be some criteria what makes something a top-level h2 ingredient vs just having it deeper in the outline.

---

#### Prefixed pages

> Some of them are no longer supported by anyone, and I think we should archive these.

Yes! Recently, Daniel and I came up with [criteria for irrelevant features](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features) that we can remove from BCD and archive MDN pages. I think we should go ahead and archive more material for things no one can use anyway.

**Comment by ddbeck** [comment]
Thanks for the follow up comment, Will. I think you helped me understand your thinking on this stuff a lot better. Having got that:

Re: `prose.syntax` — I now see the distinction you're trying to make between `prose.syntax` and `data.formal_definition_and_syntax`. I'm fine with these being distinct. For what it's worth, it was the case being made for removing `{{csssyntax}}` that sold me on this—if the selector content is going to get better, it's probably going to happen in part by removing `{{csssyntax}}`, at which point the ingredients would diverge again anyway.

Re: `H2#Allowable/permitted properties` — I see Florian's point about moving them around and I'll defer to the two of you about what to actually do with that. My position on structuring infrequently used things is that it gives a name to something we can fix: expanding the use of that ingredient (because it's underutilized), eliminating the use of the ingredient (because it's unhelpful), or finding a superstructure to move it into (e.g., an `h3` in some more-frequently used ingredient). In the near term, I think it's OK to simply name these things—cleaning them up or applying deep structure may be appealing to the rest of the content team or the community, once we're in position to bring them into this work.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/stumptown-content/pull/488.
