### ISSUE TITLE
Shorter titles for the related content?

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-content#76]
See screenshot in https://github.com/mdn/stumptown-renderer/pull/58

This is a very specific reference to the existing MDN pages which displays a different title for certain elements in the sidebar compared to the actual title when you get to the page. 

The stumptown-renderer is dumb and will just display the `title` key from the packaged JSON so if we want to have different titles in the sidebar compared to the document page, here's the place to resolve that. 

****

**Acceptance criteria:**
* we have a way to represent short titles in stumptown content, and the short title is included in the JSON
* the renderer uses short titles when rendering the sidebar

**Comment by peterbe** [comment]
We could, in the front-matter have an optional key called "short_title". So, when we generated the `related_content` we do something like `related_content.title = doc.meta.short_title || doc.meta.title`

**Comment by peterbe** [comment]
Somewhat separate to that is that on MDN the sidebar short titles are displayed with monospace font. I.e. in the sidebar it's `<code>&lt;video&gt;</code>` but when you click on it, it's `&lt;video&gt: The Video Embed element`

Here I think renderer needs to be a bit smarter so it knows to render the titles slightly differently. E.g. 
```
<li>{node.is_code ? <code>{node.title}</code> : node.title}</li>
```

But what else is there like that? ...so that we think ahead a little. What about the icons? I think it would make sense for stumptown-content to have a secret language and the in the renderer we do the visual decisions. E.g. 
```
<li className={node.is_deprecated ? 'deprecated-sidebar-item' : null}>
{node.title}
</li>
```

**Comment by wbamberg** [comment]
On short titles, yes, I think we ought to do this and I think we should do basically what you say in https://github.com/mdn/stumptown-content/issues/76#issuecomment-515200733.

Also this isn't just about length, but also context. For example, recently as an SEO experiment @a2sheppy tried making some CSS pages have long titles, so rather than "margin" it said something like "CSS margin property". This didn't stick in the end, but while it was going on these titles were showing up in the sidebar, like

```
CSS
    Properties
        CSS background property
        CSS background-color property
        CSS border property
```

...it's obvious from the context that it's a CSS property, so saying it again in the link text just looks silly. It's also harder to scan this way.

So yes, it feels as if we should let pages have different titles from their names in the sidebar (or any other place where the context is already given).

**Comment by a2sheppy** [comment]
> Here I think renderer needs to be a bit smarter so it knows to render the titles slightly differently. E.g.

> ```
> <li>{node.is_code ? <code>{node.title}</code> : node.title}</li>
> ```
> 
> But what else is there like that? ...so that we think ahead a little. What about the icons? I think it would make sense for stumptown-content to have a secret language and the in the renderer we do the visual decisions. E.g.

That could potentially be a good idea. Have a few special codes that can be used to indicate that something should be presented a certain way when possible, perhaps. Some special characters or something. There are a number of ways we could do it.

Or, you know, we could just make the sidebar renderer use some sort of a template mechanism that could be configured to know that it should be using a specific part of the title, or some other text, in a given style.

**Comment by wbamberg** [comment]
> > Here I think renderer needs to be a bit smarter so it knows to render the titles slightly differently. E.g.
> 
> > ```
> > <li>{node.is_code ? <code>{node.title}</code> : node.title}</li>
> > ```
> > 
> > 
> > But what else is there like that? ...so that we think ahead a little. What about the icons? I think it would make sense for stumptown-content to have a secret language and the in the renderer we do the visual decisions. E.g.
> 
> That could potentially be a good idea. Have a few special codes that can be used to indicate that something should be presented a certain way when possible, perhaps. Some special characters or something. There are a number of ways we could do it.
> 
> Or, you know, we could just make the sidebar renderer use some sort of a template mechanism that could be configured to know that it should be using a specific part of the title, or some other text, in a given style.

I'd like if possible to separate this from the short_title issue. But also: to be honest I don't see a great deal of value in the icons and code styling in the sidebar, and I'm not sure it's worth inventing extra bits of grammar to support it. I'd really like to keep things simple here.

**Comment by a2sheppy** [comment]
I think maintaining the code styling in the sidebar is crucial because we
need consistency of appearance. We go to a pretty significant amount of
effort to try to maintain a style standard; not adhering to it in the
sidebar would be a mistake.

On July 29, 2019 at 5:32:13 PM, wbamberg (notifications@github.com) wrote:

I'd like if possible to separate this from the short_title issue. But also:
to be honest I don't see a great deal of value in the icons and code
styling in the sidebar, and I'm not sure it's worth inventing extra bits of
grammar to support it. I'd really like to keep things simple here.


Eric Shepherd
Senior Technical Writer
MDN Web Docs <https://developer.mozilla.org/>
Blog: https://www.bitstampede.com/

**Comment by wbamberg** [comment]
* https://github.com/mdn/stumptown-content/pull/142 added `short_title` to the content
* https://github.com/mdn/stumptown-renderer/pull/133 rendered them in sidebars.
